statusautomation_download:
  path: statusautomation/download
  methods: [GET]
  defaults:
    _controller: PrestaShop\Module\Statusautomation\Controller\FileAdminController::downloadAction
    _legacy_controller: 'FileAdminController'
    _legacy_link: 'FileAdminController'
statusautomation_upload:
  path: statusautomation/upload
  methods: [POST]
  defaults:
    _controller: PrestaShop\Module\Statusautomation\Controller\FileAdminController::uploadAction
    _legacy_controller: 'FileAdminController'
    _legacy_link: 'FileAdminController'
statusautomation_upload_import:
  path: statusautomation/upload_import
  methods: [POST]
  defaults:
    _controller: PrestaShop\Module\Statusautomation\Controller\FileAdminController::uploadImportAction
    _legacy_controller: 'FileAdminController'
    _legacy_link: 'FileAdminController'
statusautomation_update_is_verified_toggle:
  path: /statusautomation/customers/{customerId}/update-is-verified
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Statusautomation\Controller\VerifiedStatusController::updateStatusAction'
    _legacy_controller: AdminCustomers # Optional, just for legacy links
    _legacy_link: AdminCustomers:updateCustomerGroup